
#define IDR_WAVE_BOAT_ANCHOR_DOWN       103
#define IDR_WAVE_BOAT_ANCHOR_UP         104
#define IDR_WAVE_SUB_ANCHOR_DOWN        105
#define IDR_WAVE_SUB_ANCHOR_UP          106
#define IDR_WAVE_JETSKI_ANCHOR_DOWN		107
#define IDR_WAVE_JETSKI_ANCHOR_UP		108
#define IDR_WAVE_PLANE_ANCHOR_DOWN		109
#define IDR_WAVE_PLANE_ANCHOR_UP		110

